name: Upstream Showcase
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sdk-platform-java @ main
        uses: actions/checkout@v3
        with:
          path: sdk-platform-java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install sdk-platform-java to local maven repository
        shell: bash
        working-directory: sdk-platform-java
        run: mvn install -B -ntp -T 1C -DskipTests
      - name: Install showcase to local maven repository
        shell: bash
        working-directory: sdk-platform-java/showcase
        run: mvn install -B -ntp -T 1C -DskipTests

      - name: Cache Bazel cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('grpc/WORKSPACE', 'sdk-platform-java/WORKSPACE', 'protobuf/WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-${{ hashFiles('grpc/WORKSPACE', 'sdk-platform-java/WORKSPACE', 'protobuf/WORKSPACE') }}

      - name: Update Showcase version to 0.0.2-SNAPSHOT
        working-directory: sdk-platform-java/showcase
        shell: bash
        run: mvn versions:set -B -ntp -DnewVersion=0.0.2-SNAPSHOT

      - name: Update proto and grpc versions
        working-directory: sdk-platform-java/gax-java
        shell: bash
        run: |
          sed -i '/version.io_grpc=.*/ s/=.*/=1.55.1/' dependencies.properties
          sed -i '/version.com_google_protobuf=.*/ s/=.*/=3.23.1/' dependencies.properties
          cat dependencies.properties

      - name: Run code generation bazel build ${{ matrix.googleapis-bazel-target }}
        working-directory: sdk-platform-java/showcase
        shell: bash
        run: |
          mvn compile -B -ntp -Pupdate

      - working-directory: sdk-platform-java/showcase
        shell: bash
        run: git diff

      - name: Clirr Check
        working-directory: sdk-platform-java/showcase
        shell: bash
        run: mvn -B -ntp clirr:check -Dclirr.skip=false -DcomparisonVersion=0.0.1-SNAPSHOT
